### PR TITLE
add mummer4

### PR DESCRIPTION
**Pull request by MrTomRod**
This pull request is incomplete.

See issue #106.

### CODE REVIEW

**Comment by robertaboukhalil** [comment]
Thanks @MrTomRod! I made changes to branch to get it into biowasm here: https://github.com/MrTomRod/biowasm/pull/1

**Comment by MrTomRod** [comment]
I added another minor detail: `python3.7` is not available in the container specified in `CONTRIBUTING.md`. (It's `python 3.8`.) https://github.com/biowasm/biowasm/pull/107/commits/df1ed5d4fb45691e96ac281f3035f4b87ebe3eb0

**Review by robertaboukhalil — APPROVED** [review]

**Comment by robertaboukhalil** [comment]
It's been deployed, thanks for contributing! https://biowasm.com/cdn/v3/mummer4/4.0.0rc1/

If you build an app with this, do let me know, I'm always curious to see what others build with biowasm 🙂

**Comment by MrTomRod** [comment]
Thanks a lot!

I'm building a simple browser-only dotplot viewer for small genomes using plotly-js. It can already use mummer/nucmer and minimap2. What's missing is gene annotations on the x-y-axes. In the end, at least, there will be an online app where you can drag/drop gbk or fasta files and get a simple dotplot. I'm considering replacing Maria Nattestad's [Dot](https://github.com/MariaNattestad/dot) which I use in my software [OpenGenomeBrowser](https://opengenomebrowser.github.io/) with this.

I'm also working on a semi-automatic but fully interactive microbial assembly curation tool inspired by [Trycycler](https://github.com/rrwick/Trycycler). But there, I need it to be really fast, so I'll probably use the backend...

**Pull request merged**
