### PR TITLE
Updated ViralConsensus to v0.0.5

### PR DESCRIPTION
**Pull request by niemasd**

### CODE REVIEW

**Review by robertaboukhalil — COMMENTED** [review]
Hey Niema! Can you also add version `0.0.5` to this file: https://github.com/biowasm/biowasm/blob/main/biowasm.json#L428-L430 so it gets picked up

**Comment by niemasd** [comment]
@robertaboukhalil Woops, thanks for catching that! Will do ASAP. Should I also add v0.0.4, which is also in its own branch on the ViralConsensus repo?

**Comment by robertaboukhalil** [comment]
It's not required, but if you want it to be accessible on the CDN, then yes please!

**Comment by niemasd** [comment]
Great, thanks! Just added it to this PR

**Comment by niemasd** [comment]
Also realized that I didn't add example files for 0.0.4 and 0.0.5, so I just added those now. So hopefully should be good to go! Please let me know if you need anything else

**Review by robertaboukhalil — APPROVED** [review]
Thanks!

**Comment by robertaboukhalil** [comment]
Just fyi this is erroring out: https://github.com/biowasm/biowasm/issues/97, I'll investigate it more closely later this week

**Pull request merged**
