### PR TITLE
add mafft

### PR DESCRIPTION
**Pull request by orangeSi**
mafft is https://mafft.cbrc.jp/alignment/software/

### CODE REVIEW

**Comment by orangeSi** [comment]
@robertaboukhalil thanks the instructions at https://github.com/biowasm/biowasm/pull/94

**Comment by robertaboukhalil** [comment]
Thanks @orangeSi, at a glance this looks great, thank you! I'll test it more extensively in the coming days.

**Comment by robertaboukhalil** [comment]
Update: I should have time to review by this Friday.

**Review by robertaboukhalil — APPROVED** [review]

**Comment by robertaboukhalil** [comment]
@orangeSi This has been deployed: https://biowasm.com/cdn/v3/mafft/7.520, thanks so much for your contribution!

**Pull request merged**
