### PR TITLE
add mafft software

### PR DESCRIPTION
**Pull request by orangeSi**
mafft is https://mafft.cbrc.jp/alignment/software/

### CODE REVIEW

**Comment by orangeSi** [comment]
commit done~

**Comment by orangeSi** [comment]
commit done now~

**Comment by robertaboukhalil** [comment]
Thanks @orangeSi! Could you follow the instructions here so that there's a repo connected to the PR instead of `wget https://gitlab.com/sysimm/mafft/-/archive/v7.520/mafft-v7.520.tar.gz`: https://github.com/biowasm/biowasm/blob/main/CONTRIBUTING.md#add-a-new-tool-to-biowasm. That way we can have multiple versions of the same tool without needing to update that script. Thanks!

**Comment by orangeSi** [comment]
ok, I will try that~

**Pull request closed without merging**
