### PR TITLE
Updated ViralConsensus to v0.0.2 (and updated some other tools)

### PR DESCRIPTION
**Pull request by niemasd**
Patches a somewhat important bug re: spurious insertions when sequencing is deep enough

### CODE REVIEW

**Comment by robertaboukhalil** [comment]
Hey Niema! To do this, we'll need to update `biowasm.json` to add the new versions to each tool, e.g. https://github.com/biowasm/biowasm/blob/main/biowasm.json#L351-L362.

I'll take a look and make sure the new versions of fastp/tn93/viralconsensus all compile to WebAssembly successfully.

**Comment by niemasd** [comment]
Hey, Robert! Ah, thanks for letting me know! I just updated the `biowasm.json` file to add the new versions. I undid my update of `fastp` because I realized you had patches to it, and I didn't feel like messing with it (it's not critical; I just thought I'd update it for you while I was at it). The only important ones are ViralConsensus (which patched a somewhat important bug) and tn93 (which also patched a bug, albeit not as important)

**Comment by niemasd** [comment]
And I also updated how FastTree is compiled (it's generally better to use double precision when possible, and I think the bottleneck for BioWASM executions of FastTree will be bound by runtime rather than memory)

**Comment by robertaboukhalil** [comment]
Looks good, thanks! To test this, I'll merge this to a branch on this repo so I can deploy it to staging

**Review by robertaboukhalil — APPROVED** [review]
Looks good, thanks! To test this, I'll merge this to a branch on this repo so I can deploy it to staging

**Pull request merged**
